model:
  # download the network at https://files.sri.inf.ethz.ch/eran/nets/onnx/mnist/convBigRELU__DiffAI.onnx
  onnx_path: convBigRELU__DiffAI.onnx # update to your own path
  input_shape: [1, 1, 28, 28]
data:
  dataset: MNIST_ERAN
  select_instance: [7, 9, 14, 32, 44, 68, 110, 112, 122, 145, 225, 330, 566, 589, 614, 746, 863, 916, 949, 988]
specification:
  epsilon: 0.225 # 20 properties
attack:
  pgd_restarts: 100
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
bab:
  timeout: 300
  branching:
    reduceop: max
