general:
  complete_verifier: bab-refine
model:
  onnx_path: vnncomp2021/benchmarks/mnistfc/mnist-net_256x6.onnx # Please update this path to point to the VNN-COMP 2021 repo
  input_shape: [-1, 1, 28, 28]  # This onnx model has input shape [-1, 784] which is not compatible with our MIP solution
data:
  dataset: MNIST
  select_instance: [1, 3, 27, 30, 32, 35, 48, 51, 54, 56, 60, 68, 69, 71, 72, 77, 85, 88, 90, 102, 103, 129] #22
specification:
  epsilon: 0.05
solver:
  batch_size: 4096
  beta-crown:
    iteration: 20
    lr_beta: 0.03
    enable_opt_interm_bounds: True
  mip:
    parallel_solvers: 32
    solver_threads: 1
    refine_neuron_time_percentage: 0.8
  start_save_best: -1
bab:
  timeout: 300
  branching:
    candidates: 5
    reduceop: max
attack:
  attack_mode: diversed_PGD
  pgd_restarts: 100
