model:
  # download the network at https://files.sri.inf.ethz.ch/eran/nets/onnx/mnist/skip__DiffAI.onnx
  onnx_path: skip__DiffAI.onnx # update to your own path
  input_shape: [1, 1, 28, 28]
data:
  dataset: MNIST_ERAN
  select_instance: [9, 12, 21, 41, 42, 49, 52, 61, 64, 72, 79, 84]
specification:
  epsilon: 0.18 # 12 properties
attack:
  pgd_restarts: 100
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
bab:
  timeout: 300
  branching:
    reduceop: max
