model:
  # download the network at https://files.sri.inf.ethz.ch/eran/nets/onnx/mnist/convBigRELU__DiffAI.onnx
  onnx_path: convBigRELU__DiffAI.onnx # update to your own path
  input_shape: [1, 1, 28, 28]
data:
  dataset: MNIST_ERAN
  select_instance: [8, 47, 52, 53, 146, 208, 365, 500, 535]
specification:
  epsilon: 0.228 # 9 properties
attack:
  pgd_restarts: 100
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
bab:
  timeout: 300
  branching:
    reduceop: max
