# Configuration file for running the sri_resnet_a benchmark (all properties).
general:
  root_path: vnncomp2022_benchmarks/benchmarks/sri_resnet_a # Please update this path to point to your own VNN-COMP 2022 repo
  csv_name: instances.csv
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
data:
  dataset: CIFAR
  select_instance: [25, 30, 46, 48, 53, 55, 56, 59, 65] # 9 properties
solver:
  batch_size: 1024
  beta-crown:
    lr_beta: 0.05
    iteration: 10
  prune_after_crown: True
bab:
  initial_max_domains: 100
  branching:
    method: kfsb-intercept-only
    reduceop: max
    candidates: 10
  interm_transfer: False
attack:
  pgd_order: middle