# self-defined epsilon property 
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
  onnx_path: vnncomp2022_benchmarks/benchmarks/sri_resnet_a/onnx/resnet_3b2_bn_mixup_adv_4.0_bs128_lr-1.onnx # Please update this path to point to your own VNN-COMP 2022 repo
data:
  dataset: CIFAR_ERAN
  select_instance: [1, 14, 15, 18, 20, 23, 41, 44, 50, 67, 84, 89, 90, 92, 97, 99, 108, 111, 114, 116, 137, 142, 148] #23
specification:
  epsilon: 0.0033
solver:
  batch_size: 1024
  beta-crown:
    lr_beta: 0.05
    iteration: 10
  prune_after_crown: True
bab:
  timeout: 300
  initial_max_domains: 100
  branching:
    method: kfsb-intercept-only
    reduceop: max
    candidates: 10
  interm_transfer: False
attack:
  pgd_order: middle